### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by Xiangzhaohong** [maudzung/Super-Fast-Accurate-3D-Object-Detection#1]
Thanks for your great work!
Is there any idea for training my own dataset to test this project?

**Comment by maudzung** [comment]
Hi @Xiangzhaohong 

You are welcome. 
To use the source code with other datasets, first, you need to convert the dataset to KITTI format. (Of course, you can manipulate the code to load bev_maps and build targets correctly in the [kitti_dataset.py](https://github.com/maudzung/Super-Fast-Accurate-3D-Object-Detection/blob/master/src/data_process/kitti_dataset.py) file). Second, please take a look at [kitti_configs](https://github.com/maudzung/Super-Fast-Accurate-3D-Object-Detection/blob/master/src/config/kitti_config.py), then modify the configs as you want.

**Comment by Xiangzhaohong** [comment]
@maudzung thanks for reply.

**Comment by rajeshchiplogictech** [comment]
Hi @maudzung , 

i want to train my own dataset. but i dont know what values i changed in kitti_configs. i see boundry paramters like this boundary = {
    "minX": 0,
    "maxX": 50,
    "minY": -25,
    "maxY": 25,
    "minZ": -2.73,
    "maxZ": 1.27
}.
so how i get this values from my dataset. i have .las file only.
