### ISSUE TITLE
How to run it on Kitti odometry dataset?

### ISSUE THREAD

**Issue by Gatsby23** [maudzung/Super-Fast-Accurate-3D-Object-Detection#6]
I'm sorry. I'm a fresh man to deep learning. Now, I can run the demo_front.py to run the kitti detection test data. But how to use it in kitti odometry velodyne dataset ? such as 00 sequence ? Can you give me some examples？

**Comment by maudzung** [comment]
Hi @Gatsby23 
I'm sorry. I have no experience in it. I'll try it later but I'm not sure when I can do it.

**Comment by Gatsby23** [comment]
> Hi @Gatsby23
> I'm sorry. I have no experience in it. I'll try it later but I'm not sure when I can do it.
I suppose that your code could use on different Lidar scan, as long as it follows the kitti format？ Right？
